### ISSUE TITLE
Atom remote access sometimes only saves to temporary local files without changing the real remote files.

### ISSUE THREAD

**Issue by ChantalJuntao** [JunoLab/JunoDocs.jl#40] opened 2019-09-13 03:19 UTC
I'm not sure if this is the right place to complain about remote access issues. In general, I really appreciate that if I lost connection to remote or accidentally shut down Atom, it preserves my open tabs. However, there is this issue where if you leave remote files open on Atom when you shut it down, it opens them up from the local temporary files before you specify where you want to remote access, and then do not connect those open local files with the remote ones. 

This has been a real problems for me as I have, on several occasions, thought that I was accessing remote files, when I was actually saving to local files, which made debugging programs that frequently crash and require restarting more confusing for me than usual. I also once lost a month of work when I opened a remote file and it overrode the temporary local file I didn't realize I was actually saving to. 

I understand that this could be an issue if users modified the remote files through a different remote access in-between remote Atom sessions. However, is there any way to make temporary files sync with identical remote versions, and prevent temporary files from being overridden by remote files if their content differs?

**Comment by pfitzseb** [comment] 2019-09-13 07:50
I think this is a duplicate of https://github.com/h3imdall/ftp-remote-edit/issues/60.

In general, that repository is the right to place for these kinds of reports, so I'll close this one here.

**Closed as completed by pfitzseb** 2019-09-13 07:50 UTC
